database:
  host: localhost
  port: "5432"
  user: postgres
  password: postgres
  name: pr_manager_db
  sslmode: disable

server:
  host: "0.0.0.0"
  port: "8081"

logger:
  level: info
  format: console
